### ISSUE TITLE
Same popup regardless of which pin I click on

### ISSUE THREAD

**Issue by 2016rshah** [tsurantino/roadtrip#2]
The popup screen with more information contains a link to the most recently found location regardless of which pin you click on. You can see examples in the images below:

![screen shot 2015-08-25 at 10 09 44 pm](https://cloud.githubusercontent.com/assets/6821244/9484129/1740f276-4b76-11e5-895f-add2d80ce19b.png)
![screen shot 2015-08-25 at 10 09 42 pm](https://cloud.githubusercontent.com/assets/6821244/9484131/1b3d68dc-4b76-11e5-9534-41e4e2a507b6.png)
![screen shot 2015-08-25 at 10 09 35 pm](https://cloud.githubusercontent.com/assets/6821244/9484132/1fa00128-4b76-11e5-88f1-34342a8dbf2d.png)
![screen shot 2015-08-25 at 10 09 32 pm](https://cloud.githubusercontent.com/assets/6821244/9484135/22eafff4-4b76-11e5-9256-f7b5de5de22d.png)

**Comment by tsurantino** [comment]
Hey! Thanks for pointing this out. I just updated the repo which fixes this issue. It's associated with another change where I tried to get all open InfoWindows to close when you tried to open a new one. I've reverted that change, which also addresses this behavior. 

See https://github.com/tsurantino/roadtrip/commit/c473b15289af33e840f75451ea22378895b06c22
